name: On Pull Request

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/**'

jobs:
  small-test:
    name: Small Test
    uses: ./.github/workflows/test-small.yml
    with:
      with-coverage: true

  lint:
    name: Lint and Format
    uses: ./.github/workflows/test-lint.yml

  coverage:
    name: Coverage
    needs: [small-test]
    uses: ./.github/workflows/test-coverage.yml
    with:
      coverage-threshold: 80