name: Test - Medium

on:
  workflow_call:

jobs:
  test:
    name: Run Medium Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache: true

      - name: Verify dependencies for main project
        run: go mod verify

      - name: Verify dependencies for acceptance tests
        working-directory: tests/acceptance
        run: go mod verify

      - name: Run medium tests
        working-directory: tests/acceptance
        run: go test -tags=medium ./...