name: Test - Coverage

on:
  workflow_call:
    inputs:
      coverage-threshold:
        required: true
        type: number
        description: 'Minimum coverage threshold percentage'

jobs:
  coverage:
    name: Check Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Calculate coverage
        id: calc-coverage
        run: |
          coverage=$(go tool cover -func=coverage.txt | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "coverage=$coverage" >> $GITHUB_OUTPUT

      - name: Generate coverage report
        run: |
          cat << EOF > $GITHUB_STEP_SUMMARY
          # Test Coverage Report

          ## File Coverage Details
          \`\`\`
          $(go tool cover -func=coverage.txt)
          \`\`\`

          ## Coverage Status
          EOF

      - name: Check coverage threshold
        run: |
          coverage=${{ steps.calc-coverage.outputs.coverage }}
          
          if (( $(echo "$coverage < ${{ inputs.coverage-threshold }}" | bc -l) )); then
            cat << EOF >> $GITHUB_STEP_SUMMARY
          ### ⚠️ Coverage Alert

          Test coverage is below required threshold:
          - Current: $coverage%
          - Required: ${{ inputs.coverage-threshold }}%
          EOF
            exit 1
          else
            cat << EOF >> $GITHUB_STEP_SUMMARY
          ### ✅ Coverage Check Passed

          Coverage requirements met:
          - Current: $coverage%
          - Required: ${{ inputs.coverage-threshold }}%
          EOF
          fi