name: Test - Medium

on:
  workflow_call:

jobs:
  test:
    name: Run Medium Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: tests/acceptance
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache: true

      - name: Tidy dependencies
        run: go mod tidy

      - name: Run medium tests
        run: go test -tags=medium ./...